settings:
  digits: 3
  itemformat: yaml
  parent: APP-QL
  prefix: APP-QL-PBN
  sep: '-'
attributes:
  defaults:
    doc:
      title: Primary Beneficiaries
      by: QA Team
      major: '0'
      minor: '.0'
      copyright: "copyright: '© 2025 AIF - *All rights reserved*'"
