settings:
  digits: 5
  itemformat: yaml
  parent: OP
  prefix: LLR
  sep: '-'
attributes:
  defaults:
    doc:
      title: "Low Level Requirements"
      by: "QA Team"
      major: "1"
      minor: ".0"
      copyright: "© 2025 AIF - *All rights reserved*"